### PR TITLE
Replace three intake commands with a parameter

### PR DESCRIPTION
**Pull request by phroa**
Per Dana's comments, having duplicate code like that isn't great.

### CODE REVIEW

**Comment by phroa** [comment]
I haven't tested this yet.

**Comment by dbadb** [comment]
i'm wondering if the isFinished method is, er, finished.  For this variety of "on-shot" commands, I believe it may be more correct for isFinished to return true (?).  To be completely clear on this, it would be nice to log the start and end methods.

**Comment by phroa** [comment]
When it does return true, the motor spins for 10ms (or whatever a scheduler tick is) then stops, not really useful for anything. A one-shot command to 'fire one ball' should probably be a CommandGroup to start, wait, then stop the motor.

**Comment by dbadb** [comment]
ah - makes sense... So perhaps we need some comments in the execute method.  This overlaps with the topic of "motor safety" in which a motor needs to be tickled periodically when on.   So an alternate (not necessarily better) approach is to return true when the motor is turned off and return false if where actively running the motor.

**Comment by binnur** [comment]
Why is there a separate mode (and command??) to count encoder ticks?  
> System.out.println(m_intake.getEncoder());

**Pull request merged**
