### PR TITLE
Motion replay/performance capture/recording

### PR DESCRIPTION
**Pull request by phroa**

### CODE REVIEW

**Comment by dbadb** [comment]
minor integration issue wrt to declan's recent change.
conflict with noah's active pull request wrt button assignments.
currently this implementation only supports a single recording. It's probably in the cards to support named recordings and presumably load these from a dashboard string selector.

**Comment by phroa** [comment]
```
    [javac] /home/travis/build/Spartronics4915/2017-STEAMworks/src/org/usfirst/frc/team4915/steamworks/OI.java:117: error: cannot find symbol

    [javac]         m_turnIMUStart.whenPressed(new TurnSequenceCommandGroup(m_robot.getDrivetrain()));

    [javac]                                        ^

    [javac]   symbol:   class TurnSequenceCommandGroup

    [javac]   location: class OI
```

Just updated your merge commit, think I fixed it.

**Comment by loqoman** [comment]
This is purely for recording/archiving purposes?

**Comment by phroa** [comment]
The idea is we'll record `x` different tracks and play them back during autonomous depending on our starting position and strategy.

**Comment by loqoman** [comment]
So there is no visual recording being done quite yet (?)

When you say 'track' do you mean, some form of location system that keeps track of motor and servo movement?

**Comment by phroa** [comment]
Joystick inputs are what we record and replay here.

The Talon SRX motor controllers we use have a "true" motion capture system built in where we can run each motor individually at a certain speed for a certain duration, but as the official usage guide includes, among other things, an excel macro to output the actual motor profiles, it's  not worth it.

There's no vision system this year.

**Comment by loqoman** [comment]
Ok, fantastic. Reason I was interested was that I was tasked by Declan to start building a RoboRIO comparable vision system for next year, and was wondering if you guys were *currently* doing anything with visuals.

Thanks.

**Pull request merged**
